name: Trigger auto deployment for hackfest-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hackfest-container-AutoDeployTrigger-bef1dc4d-3c44-4071-936e-e463048a86fd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HACKFESTCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HACKFESTCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HACKFESTCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: hackfestbackend-d0cbekfpe9ewbkdc.azurecr.io
          registryUsername: ${{ secrets.HACKFESTCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HACKFESTCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: hackfest-container
          resourceGroup: hackfest-group
          imageToBuild: hackfestbackend-d0cbekfpe9ewbkdc.azurecr.io/hackfest-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


